apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dpplint-tls
spec:
  secretName: dpplint-tls
  issuerRef:
    group: cert-manager.io
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - dpplint.ownyourdata.eu
